version: '3.4'

services:
  catalogdb:
       image: mongo

  basketdb:
       image: redis:alpine

  orderdb:
       image: mcr.microsoft.com/mssql/server

  rabbitmq:
       image: rabbitmq:3-management-alpine
  #portainer:
  #     image: portainer/portainer-ce

  #discountdb:
  #  image: postgres

  #pgadmin:
  #  image: dpage/pgadmin4
    
  


  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/CatalogApi/Dockerfile 

  basketapii:
    image: ${DOCKER_REGISTRY-}basketapii
    build:
      context: .
      dockerfile: src/Basket/BasketApii/Dockerfile

  orderingapi:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Ordering/OrderingApi/Dockerfile

#  discount.api:
#    image: ${DOCKER_REGISTRY-}discountapi
#    build:
#      context: .
#      dockerfile: src/Discount/Discount.Api/Dockerfile

#volumes:
#  mongo_data:
#  portainer_data:
#  postgres_data:
#  pgadmin_data:

  
